Anastasiya_Kochetkova_JavaRush_Project_1
mracobestia/javarush-cryptoanalyser pull request #1
Opened 2022-03-18 13:43 UTC by mracobestia

2022-03-19 16:41 UTC, AndryLat requested changes

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/IllegalCharacter.java
> +public class IllegalCharacter extends RuntimeException {
Все эксепшены нужно называть с окончанием Exception, то есть IllegalCharacterException

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/IllegalCharacter.java
> +        System.out.println("An unknown character was passed. The program is being hacked!");
Никогда так не делай:)

Эксепшены это такие объекты, которые мы бросаем и дальше где-то ловим. В них не должно быть никакой бизнес логики, максимум логика по хранению каких-=то данных об ошибке.

Вторая проблема: Код не переиспользуемый. Сегодня ты пишешь код для консольного приложения, а завтра это превращается в веб сервис, или, банально, ты все результаты будешь писать в файл. ЧТо тогда? СОздавать копии классов с другим выводом? это нашрушение принципа DRY. А решение очень простое - метод должен на вход получить данные, а вернуть результат. И дальше ты делаешь с этим результатом, что хочешь.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/Main.java
> +    public static final String ENCRYPT_MODE = "encrypt";
Зачем константы публичными делать? их кто-то еще будет использовать?

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/Main.java
> +                Hello, friend! If you want to use Caesar cipher program, please, select the mode:
Можно весь текст вынести в константу:) тогда метод читабельнее станет.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/Main.java
> +        while(!line.equals(EXIT_MODE) && !result.equals(EXIT_MODE));
Что если line или result окажутся null? правильно, вылетит NPE. Чтобы такого не было, всегда вызываем equals у строки, которая менее всего вероятна быть null. В примере тут - надо писать EXIT_CODE.equals(...)

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +    private ConsoleInterface() {}
работа через статический контекст не желательна, но сейчас простительна.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +        HashMap<String, String> parameters = getParameters();
При работе с коллекциями мы с Антоном не раз делали акцент, что нужно для объявления переменных типа коллекция использовать интерфейс.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +            ex.printStackTrace();
Для пользователя такая обработка ошибок выглядит пугающе.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +    private static boolean isFilePathValid(String filePath) {
Почему у тебя класс, который отвечает за взаимодействие с пользователем, отвечает еще и за валидацию? SOLID - S

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +            e.printStackTrace();
Ужасная обработка ошибок. Пользователь этого метода никогда не узнает, пошло что-то не так или все хорошо.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +    public static void decrypt(String inputFilePath, String outputFilePath, int key) throws IllegalCharacter {
Ты сделала RuntimeException, он анчекед, зачем  throws IllegalCharacter ?

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +            throw new IllegalCharacter();
А можно немного деталей в эксепшен добавить, чтолбы тот, кто будет анализировать проблему, мог хоть что-то понять, что пошло не так?

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +        boolean isSymbolWrite = false;
Не понимаю смысла переменной из имени.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +            String outputFilePath = newCatalog + separator + "ResultFile" + i + ".txt";
"ResultFile" + i + ".txt" лучше выносить в константы такие литералы. Потому что завтра тебе скажут изменить имя результирующего файла, потребудет много времени, чтобы найти все места. А при константах они будут сверху класса и все удобно и быстро можно бдует исправить.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +    public static void hackBruteForce(String inputFilePath) throws IllegalCharacter, IOException {
Такие громадные методы лучше разбивать на более мелкие.

2022-03-19 16:41 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +    private static boolean clearOutputFileBefore(String outputFilePath) {
Странный метод. Имя говорит об одном, делает он немного другое.

2022-03-19 16:41 UTC, AndryLat commented
В целом, все очень круто, не считая мелочей. Для первого модуля - просто отлично!

2022-03-20 17:41 UTC, mracobestia commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +            ex.printStackTrace();
@AndryLat , помоги понять, пожалуйста, что в данном случае нужно сделать?( Вместо printStackTrace() вывести какой-то свой текст ошибки через system.out.println()? Во всех вызовах .printStackTrace() в программе нужно такое проделать?

2022-03-20 17:41 UTC, mracobestia commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +            throw new IllegalCharacter();
@AndryLat , а как это сделать? Через system.out.println() сейчас какой-то свой текст вывести дополнительно? А сделать это на этом уровне или там, где мы этот эксепшн ловить будем уже?

2022-03-20 17:41 UTC, mracobestia commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +    private static boolean clearOutputFileBefore(String outputFilePath) {
@AndryLat , по смыслу хотела передать, что метод очистит файл, в который мы собираемся записывать результат шифровки/дешифровки. Вариант "clearFileBeforeWriting" лучше?)

2022-03-20 18:29 UTC, andriilatyshev commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +            ex.printStackTrace();
Если мы используем консоль, то мы должны писать юзер френдли ошибку в Systtem.err поток . По поводу заменить это на везде: мы  общаемся с пользователем только на том слое, где мы общаемся с пользователем. Если мы можем обработать ошибку (в данном слуцчае показать пользователю или что-то предпринять) - делаем это, если нет - бросаем дальше.

2022-03-20 18:29 UTC, andriilatyshev commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +            throw new IllegalCharacter();
Как минимум в IllegalCharacter вложить понятный текст с ошибкой.  А дальше его уже где-то достать и показать пользователю..

2022-03-20 18:30 UTC, andriilatyshev commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +    private static boolean clearOutputFileBefore(String outputFilePath) {
Да, будет понятнее:) либо просто clearFile 

2022-03-22 22:27 UTC, Enotik-code reviewed
Отличная работа!

2022-03-22 22:27 UTC, Enotik-code commented on src/java/com/javarush/cryptoanalyser/Main.java
> +                    yield "";
Молодец!

2022-03-22 22:27 UTC, Enotik-code commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +        if (parameters.get("exit").equals(EXIT_MODE)) {
поменять местами

2022-03-22 22:27 UTC, Enotik-code commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +        if (parameters.get("exit").equals(EXIT_MODE)) {
и можно проверить, есть ли там параметры, потому что get может  NPE  бросить

2022-03-22 22:27 UTC, Enotik-code commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +        FREQUENCE_DICTIONARY.add("ведь");
очень надеюсь что не руками это все было сделано)

2022-03-28 10:24 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/programinterface/ConsoleInterface.java
> +    private static Map<String, String> getParameters() {
Слишком длинный метод. Лучше попытаться разбить на маленькие и понятные.

2022-03-28 10:24 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/programinterface/ParameterValidation.java
> +    private static final String[] IGNORED_FILES = {".bash_history", ".bash_logout", ".bash_profile",
Это не игнорируемые файлы, а запрещенные

2022-03-28 10:24 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +                e.printStackTrace();
получается, что в любой непонятной ситуации мы вернем какую-то цифру. Не надо так. Произошла ошибка - останавливаем все и сообщаем пользователю.

2022-03-28 10:24 UTC, AndryLat commented on src/java/com/javarush/cryptoanalyser/workalgorithm/Cryptanalyser.java
> +    private static boolean clearFile(String outputFilePath) {
Как я и говорил ранее: мы пытаемся очистить файл, а когда это не получилось - мы просто вернули фолс.

2022-09-01 14:08 UTC, merged